<?php
//
// File generated by Dolibarr installer 20.0.2 on 06 Jan. 2025
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//

/////////// AJOUT /////////// 9/01/25
$dolibarr_main_log_handler = 'file';
$dolibarr_main_log_file = 'logs/dolibarr.log';
$dolibarr_main_log_level = 'DEBUG';

$dolibarr_main_url_root='http://localhost:8887/dolibarr/htdocs';
$dolibarr_main_document_root="/Applications/MAMP/htdocs/dolibarr/htdocs";
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt="/Applications/MAMP/htdocs/dolibarr/htdocs/custom";
$dolibarr_main_data_root="/Applications/MAMP/htdocs/dolibarr/documents";
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='0';
$dolibarr_main_db_name='dolibarr';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='root';
$dolibarr_main_db_pass='root';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_unicode_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='4bf2a4ad3c545873b075748c644c7b7a';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH="";
//$dolibarr_lib_TCPDF_PATH="";
//$dolibarr_lib_FPDI_PATH="";
//$dolibarr_lib_TCPDI_PATH="";
//$dolibarr_lib_GEOIP_PATH="";
//$dolibarr_lib_NUSOAP_PATH="";
//$dolibarr_lib_ODTPHP_PATH="";
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP="";
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
